### ISSUE TITLE
Local video file 

### ISSUE THREAD

**Issue by Reotch2** [PtrBld/MMM-Podcast#12]
I don’t know why I can’t figure this out. How do I call a local file? I’ve got a video of ghost images I’d like to pop up for Halloween, and it seems like your module is the only one that embeds omxplayer. I’m using videoUrl: ‘modules/Videos/file.m4v’. 

Any help would be appreciated.

**Comment by PtrBld** [comment]
Hi my module is not capable of doing this since it expects a video from an online source. 
You could fork this module, however and change the necessary parts. Maybe add some fullscreen support, too?
