### ISSUE TITLE
Possible to load custom video hosted on PI being served via Apache?

### ISSUE THREAD

**Issue by CharlesJGantt** [PtrBld/MMM-Podcast#13]
Hello i am trying to play a video feed from srv/www/html/video.mp4 via an RSS feed that is in the same folder. Is this possible? I can get it to play the German news feed only, and when I try to set it up to play the custom feed I created in var/www/html, it just locks up MagicMirror and I have to reboot the Pi.

**Comment by PtrBld** [comment]
No not with this module but I am sure there is a module around which can do this
