### ISSUE TITLE
Send notification to all modules, when video download has finished

### ISSUE THREAD

**Issue by Ax-LED** [PtrBld/MMM-Podcast#16]
@PtrBld 
Is it possible to add a notification to all modules, when video download has finished?
I think it needs modification in **node_helper.js**
`
file.on('finish', function() {
file.close(cb);			
});
`
Some notification that sends to **MMM-Podcast.js**.
From there a notification could be send to all modules like "Video_complete".

Maybe an idea if you modify/refresh your module the next time.
I use it serveral times a day, but sometimes i want to watch "Tagesschau" quicker than my Wifi connection of pi is. My pi switches automatically on and off, so it need to run some time until the video download is completed.

AxLED

**Comment by PtrBld** [comment]
Done
