### ISSUE TITLE
omxplayer install

### ISSUE THREAD

**Issue by GlenNicholls** [PtrBld/MMM-Podcast#3]
I have a quick question. Wasn´t omxplayer a default addition since wheezy? If so, do I still need to download certain things from that github link? I went there to try and download it, but the explanation for everything is not very clear.

**Comment by PtrBld** [comment]
Yes you are right.  Normally (if you are using raspbian)  you should not need to install omxplayer. However you can check if it is installed and ipdated by typing 'sudo apt-get install omxplayer' in your console.
