### ISSUE TITLE
No Sound / kein Ton beim Abspielen

### ISSUE THREAD

**Issue by RavixModz** [PtrBld/MMM-Podcast#6]
Hallo,
ich habe ein kleines Problem mit dem Modul.
Wenn ich die Tagesschau starte dann läuft zwar das Video aber es kommt kein Ton.
Youtube Videos über den Browser kann ich jedoch ohne Probleme mit Ton schauen.
Woran könnte das liegen das, das Modul keinen Ton abspielt?

Danke für Antworten

**Comment by PtrBld** [comment]
Schau mal nach welche Soundeinstellungen dein omxplayer hat.

**Comment by Picopower** [comment]
Hallo,
habe ein kleines problem mit dem Podcast Modul, es update sich nicht automatisch nach 4 stunden nur wenn ich die tasten Alt+F4 drücke oder den raspi neu starte ist ein neues Video da.
Habe schon viele Einstellungen probiert ich bin mit mein Latein am ende.
Kannst du mir helfen danke dir im Voraus.

Mit freundlichen Grüßen
olaf
